try:
    raise Exception("Foo occurred")
except:
    print ("error")
else:
    print ("else")
finally:
    print ("finally")

    
